name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and measure time
      run: |
        start=$(date +%s)
        cargo build --release
        end=$(date +%s)
        echo "Build time: $((end - start)) seconds"

    - name: Binary size
      run: |
        BIN=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].targets[] | select(.kind[] == "bin") | .name')
        SIZE=$(stat -c%s "target/release/$BIN")
        SIZE_MB=$(echo "scale=2; $SIZE/1048576" | bc)
        echo "Binary size: $SIZE_MB MB"
